### ISSUE TITLE
Readme is out of date

### ISSUE THREAD

**Issue by beeblebroccoli** [whiteShtef/dendrites#5]
The readme needs the code examples updated to match the new PEP8 update of the code.

**Comment by sbrki** [comment]
Hmm, what exactly do you mean by

>  match the new PEP8 update of the code.

? :)

**Comment by beeblebroccoli** [comment]
The PEP8 update changed the naming convention of methods from UpperCamelCase to lower_case_with_underscores, which is not reflected in the README.
For example, the `Add` method has now become the `add` method
